### ISSUE TITLE
syswatch_wdt_feed函数改为可供外部调用是否更好？

### ISSUE THREAD

**Issue by wdfk-prog** [qiyongzhong0/rt-thread-syswatch#6]
- 喂狗函数可以给外部函数调用
- 有些操作需要耗费大量时间，可能导致看门狗复位，然而平常不需要很长的看门狗时间。
- 例如flash的写入操作过长容易导致看门狗复位。
- 喂狗函数syswatch_wdt_feed给外部调用的话，就不需要重新在获取一遍看门狗设备了

**Comment by qiyongzhong0** [comment]
不建议外部喂狗操作，如果陷入有狗的外部循环，系统就完了。

**Comment by wdfk-prog** [comment]
> 不建议外部喂狗操作，如果陷入有狗的外部循环，系统就完了。

是有道理,那外部耗时操作,看门狗时间不够怎么办?
增加看门狗时间也不合适吧?

**Comment by qiyongzhong0** [comment]
看门狗是防止系统死机的，时间长些没什么的，我一般配置成10s左右。

**Comment by qiyongzhong0** [comment]
如果有长耗时操作且必须长期占用CPU，那加长看门狗时间也没什么不良影响！

**Comment by wdfk-prog** [comment]
> 如果有长耗时操作且必须长期占用CPU，那加长看门狗时间也没什么不良影响！

说的有道理.
