### ISSUE TITLE
RT-Thread 5.0.0中使用FINSH时，finsh线程超时

### ISSUE THREAD

**Issue by taocong223** [qiyongzhong0/rt-thread-syswatch#7]
问题：RT-Thread 5.0.0中使用FINSH时，finsh线程被判断为卡死，实际没有，导致复位系统（我配置成复位整个系统）
原因：syswatch_thread_switch_hook中if (to->current_priority == RT_THREAD_PRIORITY_MAX - 1)
我的措施：修改为if ((to->current_priority == RT_THREAD_PRIORITY_MAX - 1) || (to->current_priority == FINSH_THREAD_PRIORITY)) 保证finsh计数及时清除

**Comment by qiyongzhong0** [comment]
syswatch判断finsh卡死是指它长时间不释放CPU导致比它低优先级的线程无法运行。这表明finsh线程在等待接收字符时没有主动释放CPU，这里有bug，属于不正常行为，须进行修改。否则比finsh优先级低的线程得不到运行，系统部分功能会丧失，比如线程资源回收、低功耗控制等。

**Comment by taocong223** [comment]
豁然开朗，十分感谢
