### ISSUE TITLE
配置看门狗设备应提前进行

### ISSUE THREAD

**Issue by taocong223** [qiyongzhong0/rt-thread-syswatch#8]
场景：外部硬件看门狗250ms，若未及时喂狗会导致复位
原因：当前代码中，看门狗的设备配置在线程中syswatch_thread_entry，该函数需要等待调度器运行后才会启动，喂狗时间较晚
我的措施：
int syswatch_init(void)
{
    rt_thread_t tid;

    if (sw_data.init_ok)
    {
        return RT_EOK;
    }
    if (syswatch_wdt_startup() != RT_EOK) // 这里配置看门狗
    {
        LOG_E("watch dog startup fail");
        return -RT_ERROR;
    }
    syswatch_wdt_feed();
   /***其他代码**/
}
INIT_COMPONENT_EXPORT(syswatch_init);
由于INIT_COMPONENT_EXPORT阶段在初始化早期，能较早实现喂狗，而不是时间较后的线程中
另外，这种情况下，syswatch_thread_entry线程中的等待时间建议可以设置小一点，如使用rt_thread_mdelay(X_MS)

**Comment by qiyongzhong0** [comment]
如果看门狗超时时间可以调长的话，建议调长些，如果不能，则建议修改看门狗驱动，在看门狗初始化，配置等操作中加入喂狗操作，应该可以解决此类问题。

**Comment by taocong223** [comment]
硬件看门狗超时时间无法修改。
原有的syswatch是在syswatch_thread_entry中配置看门狗，线程启动的时间受到系统多个初始化阶段（INIT_BOARD_EXPORT、INIT_COMPONENT_EXPORT等）影响，会导致喂狗的不确定性（由于采用硬件看门狗），我认为可以将看门狗配置初始化放在INIT_COMPONENT_EXPORT阶段的syswatch_init，这样后续其他初始化阶段可以适当调用看门狗驱动喂狗，同时可防止初始化阶段程序跑飞

**Comment by qiyongzhong0** [comment]
syswatch_init函数执行到rt_thread_startup后，syswatch_thread_entry线程会立即得到执行，因为它优先级最高，所以只要在看门狗初始化和控制中加入喂狗操作，效果和你做的修改措施是一样的。

**Comment by taocong223** [comment]
是的，您说的是对的，启动优先级0的该线程会立刻执行。有以下问题和疑问
1.在rt-thread 5.0.0中，syswatch.c的第88行会报错，rt_thread_t 的结构体中没有name，应变更为thread->parent.name
2.rt_thread_delay(RT_TICK_PER_SECOND)中的RT_TICK_PER_SECOND换一个syswatch专用的喂狗间隔宏是否更好？
3.当前协议修改源文件后除了修改syswatch修改外需要公开项目其他源代码吗？

**Comment by qiyongzhong0** [comment]
> 是的，您说的是对的，启动优先级0的该线程会立刻执行。有以下问题和疑问 1.在rt-thread 5.0.0中，syswatch.c的第88行会报错，rt_thread_t 的结构体中没有name，应变更为thread->parent.name 2.rt_thread_delay(RT_TICK_PER_SECOND)中的RT_TICK_PER_SECOND换一个syswatch专用的喂狗间隔宏是否更好？ 3.当前协议修改源文件后除了修改syswatch修改外需要公开项目其他源代码吗？

问题1：已在lastest版本中增加了适配。
问题2：增加一个喂狗间隔宏定义，是个不错的建议。
问题3：不需要公开项目其他源码。

**Comment by qiyongzhong0** [comment]
> 是的，您说的是对的，启动优先级0的该线程会立刻执行。有以下问题和疑问 1.在rt-thread 5.0.0中，syswatch.c的第88行会报错，rt_thread_t 的结构体中没有name，应变更为thread->parent.name 2.rt_thread_delay(RT_TICK_PER_SECOND)中的RT_TICK_PER_SECOND换一个syswatch专用的喂狗间隔宏是否更好？ 3.当前协议修改源文件后除了修改syswatch修改外需要公开项目其他源代码吗？

问题1：已在lastest版本中增加了适配。
问题2：增加一个喂狗间隔宏定义，是个不错的建议。
问题3：不需要公开项目其他源码。
